### Monitors

# See https://wiki.hypr.land/Configuring/Monitors/
# monitor=,preferred,auto,1.6
monitor = ,preferred,auto,1.6

# Address issue where fonts in VSCode (and elsehwere) were pixelated
xwayland {
	force_zero_scaling = true
}