# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# Config file home

$configs = ~/.hyprconf/hypr/configs

# Variables

# Set programs that you use
$terminal = kitty
# $fileManager = dolphin
$fileManager = nautilus
$menu = wofi --show drun


# Config

source = $configs/settings.conf

source = $configs/exec.conf

source = $configs/monitor.conf

source = $configs/keybinds.conf

source = $configs/appearance.conf

source = $configs/workspace.conf

source = $configs/permissions.conf

# VSCode: address Electron app notifications text size is very small
# windowrulev2 = scaling, 1.25, class:^(code|Code|code-oss)$
