# Electron Apps

# Reference:
# https://wiki.archlinux.org/title/Electron#Configuration_files
# https://wiki.archlinux.org/title/Wayland#Electron
# https://wiki.hypr.land/Getting-Started/Master-Tutorial/#force-apps-to-use-wayland

# Flags in this file do not apply to Code/VSCode app. See: code-flags.conf

--enable-features=UseOzonePlatform

# --ozone-platform-hint=wayland (removed in Electron 38)
--ozone-platform=wayland
--ozone-platform-hint=auto

# GTK4 works better on Wayland.
# --gtk-version=4
